### PR TITLE
Changed the Admin panel(Internal and External structure) to Doctor Panel

### PR DESCRIPTION
**Pull request by zaki-hashem-chow**
1. Changed the Admin panel(Internal and External structure) to Doctor Panel(completed in 2-3 commits).
2. DB part (model and table) of Specialty portion of the doctor panel finished.

### CODE REVIEW

**Comment by ShekharUllah06** [comment]
Schedule

**Comment by ShekharUllah06** [comment]
Schedule part

**Comment by zaki-hashem-chow** [comment]
You should have merged #25 first. Please merge serially from now on. It would minimize conflicts.

**Comment by zaki-hashem-chow** [comment]
Conflicts resolved. Please merge.

**Pull request merged**
